create table OpenDota.MatchPlayerDetail(
    MatchId bigint not null,
    AccountId int not null,
	PlayerSlot int null,
	TeamNumber int null,
	TeamSlot int null,
	HeroId int null,
	HeroVariant int null,
	Item0 int null,
	Item1 int null,
	Item2 int null,
	Item3 int null,
	Item4 int null,
	Item5 int null,
	Backpack0 int null,
	Backpack1 int null,
	Backpack2 int null,
	ItemNeutral int null,
	Kills int null,
	Deaths int null,
	Assists int null,
	LeaverStatus int null,
	LastHits int null,
	Denies int null,
	GoldPerMin int null,
	XpPerMin int null,
	Level int null,
	NetWorth int null,
	AghanimsScepter int null,
	AghanimsShard int null,
	Moonshard int null,
	HeroDamage int null,
	TowerDamage int null,
	HeroHealing int null,
	Gold int null,
	GoldSpent int null,
	AbilityUpgradesArr varchar(255),
	PersonaName nvarchar(255),
	RadiantWin bit null,
	Cluster int null,
	IsRadiant bit null,
	TotalGold int null,
	TotalXp int null,
	KillsPerMin float null,
	Kda float null,
	Abandons int null,
	RankTier int null,
	
	constraint PK_OpenDota_MatchPlayerDetail primary key (MatchId,AccountId)
)
go

alter table [OpenDota].[MatchPlayerDetail] with check add constraint [FK_OpenDota_MatchPlayerDetail_Match] foreign key ([MatchId]) references [OpenDota].[Match] ([MatchId])
go

create table OpenDotaStaging.MatchPlayerDetail(
    MatchId bigint not null,
    AccountId int not null,
	PlayerSlot int null,
	TeamNumber int null,
	TeamSlot int null,
	HeroId int null,
	HeroVariant int null,
	Item0 int null,
	Item1 int null,
	Item2 int null,
	Item3 int null,
	Item4 int null,
	Item5 int null,
	Backpack0 int null,
	Backpack1 int null,
	Backpack2 int null,
	ItemNeutral int null,
	Kills int null,
	Deaths int null,
	Assists int null,
	LeaverStatus int null,
	LastHits int null,
	Denies int null,
	GoldPerMin int null,
	XpPerMin int null,
	Level int null,
	NetWorth int null,
	AghanimsScepter int null,
	AghanimsShard int null,
	Moonshard int null,
	HeroDamage int null,
	TowerDamage int null,
	HeroHealing int null,
	Gold int null,
	GoldSpent int null,
	AbilityUpgradesArr varchar(255),
	PersonaName nvarchar(255),
	RadiantWin bit null,
	Cluster int null,
	IsRadiant bit null,
	TotalGold int null,
	TotalXp int null,
	KillsPerMin float null,
	Kda float null,
	Abandons int null,
	RankTier int null,
	
	constraint PK_OpenDotaStaging_MatchPlayerDetail primary key (MatchId,AccountId)
)
go

